#@TYPE: Machine
#@NAME: Coolstream Tank
#@DESCRIPTION: Coolstream Tank (HD2, Cortex-A9, uClibc toolchain)

require conf/machine/include/tune-cortexa9hf-neon.inc

SOC_FAMILY = "coolstream"
MACHINE_FEATURES = "screen usbhost usbgadget ext2 nfs"

# Use uClibc external toolchain for Coolstream HD2
TCLIBC ?= "uclibc"
TCMODE ?= "external-coolstream"

IMAGE_FSTYPES ?= "tar.gz"
KERNEL_IMAGETYPE ?= "zImage"
UBOOT_ENTRYPOINT ?= "0x80008000"
UBOOT_LOADADDRESS ?= "0x80008000"

SERIAL_CONSOLES ?= "115200;ttyAS0"

# Coolstream-specific overrides
MACHINEOVERRIDES =. "${MACHINE}:coolstream:"
