#@TYPE: Machine
#@NAME: Coolstream HD1/NEO/ZEE/NEO2 (Nevis, glibc)
#@DESCRIPTION: Coolstream HD1/NEO/ZEE/NEO2/NEO2 Twin (ARM1176, glibc)

require conf/machine/include/tune-arm1176jzf-s.inc

SOC_FAMILY = "coolstream"
MACHINE_FEATURES = "screen usbhost usbgadget ext2 nfs"

# glibc toolchain (default)
TCLIBC ?= "glibc"
TCMODE ?= "default"

IMAGE_FSTYPES ?= "tar.gz"
KERNEL_IMAGETYPE ?= "zImage"

SERIAL_CONSOLES ?= "115200;ttyAS0"

MACHINEOVERRIDES =. "${MACHINE}:coolstream:coolstream-hd1:nevis:"
