#@TYPE: Machine
#@NAME: Coolstream Tank (apollo, uClibc toolchain)
#@DESCRIPTION: Coolstream Tank (HD2, Cortex-A9, uClibc/external toolchain)

require conf/machine/include/tune-cortexa9hf-neon.inc

SOC_FAMILY = "coolstream"
MACHINE_FEATURES = "screen usbhost usbgadget ext2 nfs"

# uClibc external toolchain for HD2 generation
TCLIBC ?= "uclibc"
TCMODE ?= "external-coolstream"

IMAGE_FSTYPES ?= "tar.gz"
KERNEL_IMAGETYPE ?= "zImage"

SERIAL_CONSOLES ?= "115200;ttyAS0"

PREFERRED_PROVIDER_virtual/kernel ?= "linux-coolstream"
PREFERRED_VERSION_virtual/kernel ?= "3.10.93"

MACHINEOVERRIDES =. "${MACHINE}:coolstream:coolstream-hd2:apollo:"
