# Layer configuration for meta-libcoolstream

BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "libcoolstream"
BBFILE_PATTERN_libcoolstream = "^${LAYERDIR}/"
BBFILE_PRIORITY_libcoolstream = "12"

# No hard deps; relies on core classes only
LAYERDEPENDS_libcoolstream = "core"
