LCONF_VERSION = "7"

BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*/*.bb"

BBFILE_COLLECTIONS += "coolstream"
BBFILE_PATTERN_coolstream := "^${LAYERDIR}/"
BBFILE_PRIORITY_coolstream = "12"

LAYERSERIES_COMPAT_coolstream = "kirkstone"

# Custom licenses (if needed)
# LICENSE_PATH += "${LAYERDIR}/files/custom-licenses"
